#include "map.h"

char map[MAP_WIDTH*MAP_HEIGHT] = \
  {
    VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,//1
    VWAL,POWR,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,//2
    VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//3
    VWAL,FOOD,VWAL,VOID,VOID,VWAL,FOOD,VWAL,VOID,VOID,VOID,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VWAL,FOOD,VWAL,VOID,VOID,VWAL,FOOD,VWAL,//4
    VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//5
    VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,//6
    VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//7
    VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//8
    VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,//9
    VWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,VOID,VWAL,VWAL,VOID,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,VWAL,//0
    VOID,VOID,VOID,VOID,VOID,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,VOID,VWAL,VWAL,VOID,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VOID,VOID,//1
    VOID,VOID,VOID,VOID,VOID,VWAL,FOOD,VWAL,VWAL,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VOID,VOID,//2
    VOID,VOID,VOID,VOID,VOID,VWAL,FOOD,VWAL,VWAL,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VOID,VOID,//3
    HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,VOID,VWAL,VOID,VWAL,HWAL,HWAL,VWAL,VOID,VWAL,VOID,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,//4

    VOID,VOID,VOID,VOID,VOID,VOID,FOOD,VOID,VOID,VOID,VWAL,VOID,VOID,VOID,VOID,VOID,VOID,VWAL,VOID,VOID,VOID,FOOD,VOID,VOID,VOID,VOID,VOID,VOID,//5

    HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,VOID,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,VOID,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,//6
    VOID,VOID,VOID,VOID,VOID,VWAL,FOOD,VWAL,VWAL,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VOID,VOID,//7
    VOID,VOID,VOID,VOID,VOID,VWAL,FOOD,VWAL,VWAL,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VOID,VWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VOID,VOID,//8
    VOID,VOID,VOID,VOID,VOID,VWAL,FOOD,VWAL,VWAL,VOID,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,VOID,VWAL,VWAL,FOOD,VWAL,VOID,VOID,VOID,VOID,VOID,//9
    VWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,VOID,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,VOID,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,VWAL,//0
    VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,//1
    VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//2
    VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//3
    VWAL,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,VWAL,//4
    VWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,VWAL,//5
    VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,VWAL,VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,//6
    VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//7
    VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,VWAL,FOOD,VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,FOOD,VWAL,//8
    VWAL,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,FOOD,VWAL,//9
    VWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,HWAL,VWAL,//0
  };
/*
#include <stdio.h>

int main (void)
{
  int all_food;
  for (int i = 0; i < WIDTH*MAP_HEIGHT; i++)
    {
      if (map[i] == FOOD)
	all_food++;
    }
  printf ("Total Food: %d\n", all_food);
  return 0;
}
*/
